"""users table

Revision ID: 88d9aac2e4a2
Revises: 
Create Date: 2019-03-10 03:10:07.244971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d9aac2e4a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('phonenumber', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('creditcard', sa.String(length=140), nullable=True),
    sa.Column('cvv', sa.String(length=140), nullable=True),
    sa.Column('expiration', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phonenumber'), 'user', ['phonenumber'], unique=True)
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startlat', sa.String(length=140), nullable=True),
    sa.Column('startlon', sa.String(length=140), nullable=True),
    sa.Column('endlat', sa.String(length=140), nullable=True),
    sa.Column('endlon', sa.String(length=140), nullable=True),
    sa.Column('distance', sa.String(length=140), nullable=True),
    sa.Column('car', sa.String(length=140), nullable=True),
    sa.Column('cost', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_timestamp'), 'trip', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_timestamp'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_user_phonenumber'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
